apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: todo-database-pv
  storageClassName: todo-db-storageclass