apiVersion: v1
kind: Service
metadata:
  name: todo-app-web-service
spec:
  type: NodePort
  selector:
    app: todo-app-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080