apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-todo-database-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <Add EBS Volume ID>
    fsType: ext4