apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-db-statefulset
spec:
  serviceName: todo-app-db-service
  replicas: 2
  selector:
    matchLabels:
      app: todo-app-mysql
  template:
    metadata:
      labels:
        app: todo-app-mysql
    spec:
      containers:
      - name: todo-app-mysql
        image: mysql:5.7
        envFrom:
          - secretRef:
              name: my-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: todo-app-mysql-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: todo-app-mysql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi