apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-todo-database-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0eee30b119a9c5b99
    fsType: ext4