apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-database-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: todo-db-storageclass
  awsElasticBlockStore:
    volumeID: vol-0322a811e54e78573
    fsType: ext4